// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yfpmekvnizkhsxlpnmhd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlmcG1la3ZuaXpraHN4bHBubWhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NTE1MTEsImV4cCI6MjA2OTEyNzUxMX0.OhTCHwIHzR_Z63SWh_H_gYuHSBEevN7rxtdt3UUyw2w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});